# 1) Problem Statement
## Breast Cancer Detection
####  Benign   -----------             Meligant***

# 2) Data Collection

In [8]:
from sklearn.datasets import load_breast_cancer

In [9]:
data=load_breast_cancer()

In [25]:
type(data)

sklearn.utils.Bunch

### About DataSet

In [3]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [5]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [6]:
data['data'].shape

(569, 30)

#### 596 no. of instances 
#### 30 attributes

In [12]:
j=0
for i in data['feature_names']:
    print(f"{i}  :  {data['data'][0][j]}")
    j+=1

mean radius  :  17.99
mean texture  :  10.38
mean perimeter  :  122.8
mean area  :  1001.0
mean smoothness  :  0.1184
mean compactness  :  0.2776
mean concavity  :  0.3001
mean concave points  :  0.1471
mean symmetry  :  0.2419
mean fractal dimension  :  0.07871
radius error  :  1.095
texture error  :  0.9053
perimeter error  :  8.589
area error  :  153.4
smoothness error  :  0.006399
compactness error  :  0.04904
concavity error  :  0.05373
concave points error  :  0.01587
symmetry error  :  0.03003
fractal dimension error  :  0.006193
worst radius  :  25.38
worst texture  :  17.33
worst perimeter  :  184.6
worst area  :  2019.0
worst smoothness  :  0.1622
worst compactness  :  0.6656
worst concavity  :  0.7119
worst concave points  :  0.2654
worst symmetry  :  0.4601
worst fractal dimension  :  0.1189


In [19]:
import pandas as pd
df=pd.DataFrame(data['data'],columns=data['feature_names'])
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [3]:
print(data['target_names'])

['malignant' 'benign']


#### 0 for cancer tumer
#### 1 for non-cancerous

In [4]:
print(data['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [5]:
data['target'].shape

(569,)

# 3) Data Preprocessing

## feature=data
## label=target

In [10]:
feature=data['data']
label=data['target']

In [11]:
from sklearn.preprocessing import StandardScaler

In [11]:
scale=StandardScaler()
feature=scale.fit_transform(feature)

j=0
for i in data['feature_names']:
    print(f"{i}  :  {feature[0][j]}")
    j+=1

mean radius  :  1.0970639814699807
mean texture  :  -2.0733350146975935
mean perimeter  :  1.2699336881399383
mean area  :  0.9843749048031144
mean smoothness  :  1.568466329243428
mean compactness  :  3.2835146709868264
mean concavity  :  2.652873983743168
mean concave points  :  2.532475216403245
mean symmetry  :  2.2175150059646405
mean fractal dimension  :  2.255746885296269
radius error  :  2.4897339267376193
texture error  :  -0.5652650590684639
perimeter error  :  2.833030865855184
area error  :  2.4875775569611043
smoothness error  :  -0.21400164666895383
compactness error  :  1.3168615683959484
concavity error  :  0.72402615808036
concave points error  :  0.6608199414286064
symmetry error  :  1.1487566671861758
fractal dimension error  :  0.9070830809973359
worst radius  :  1.8866896251792757
worst texture  :  -1.3592934737640827
worst perimeter  :  2.3036006236225606
worst area  :  2.0012374893299207
worst smoothness  :  1.3076862710715387
worst compactness  :  2.616665023512

In [20]:
df=pd.DataFrame(feature,columns=data['feature_names'])
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   worst concave points  worst symmetry  worst fractal dimension  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [12]:
label[0]

0

In [13]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [17]:
print(data['target_names'][label[0]])
print(data['target_names'][label[500]])

malignant
benign


# Train Module

### 80% - Training
### 10% - Validation
### 10% - Testing


In [22]:
569*80/100

455.2

In [12]:
# 500 Training

x_train=feature[:500]
y_train=label[:500]

#35 Validation

x_val=feature[500:535]
y_val=label[500:535]

#34 Testing

x_test=feature[535:]
y_test=label[535:]

In [28]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tensorflow

  Using cached tensorflow-2.6.0-cp38-cp38-win_amd64.whl (423.2 MB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached h5py-3.1.0-cp38-cp38-win_amd64.whl (2.7 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached grpcio-1.40.0-cp38-cp38-win_amd64.whl (3.2 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached clang-5.0-py3-none-any.whl
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
  Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Attempting uninstall: h5py
    Found existing i

## Create Neural Network

In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
model=Sequential()

model.add(Dense(64,activation='relu',input_dim=30))
model.add(Dense(32,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#### Training Begins->

In [63]:
model.fit(x_train,y_train,batch_size=5,epochs=15,validation_data=(x_val,y_val))

Epoch 1/15
100/100 [==============================] - 0s 2ms/step - loss: 0.2085 - accuracy: 0.9140 - val_loss: 0.2063 - val_accuracy: 0.9429
Epoch 2/15
100/100 [==============================] - 0s 2ms/step - loss: 0.1797 - accuracy: 0.9180 - val_loss: 0.1481 - val_accuracy: 0.9143
Epoch 3/15
100/100 [==============================] - 0s 1ms/step - loss: 0.2455 - accuracy: 0.9180 - val_loss: 0.4173 - val_accuracy: 0.8000
Epoch 4/15
100/100 [==============================] - 0s 1ms/step - loss: 0.1821 - accuracy: 0.9260 - val_loss: 0.1570 - val_accuracy: 0.8857
Epoch 5/15
100/100 [==============================] - 0s 2ms/step - loss: 0.1770 - accuracy: 0.9280 - val_loss: 0.1261 - val_accuracy: 0.9429
Epoch 6/15
100/100 [==============================] - 0s 4ms/step - loss: 0.1846 - accuracy: 0.9160 - val_loss: 0.1207 - val_accuracy: 0.9429
Epoch 7/15
100/100 [==============================] - 0s 4ms/step - loss: 0.1621 - accuracy: 0.9300 - val_loss: 0.1262 - val_accuracy: 0.9429
Epoch 

In [64]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.1790 - accuracy: 0.9412


[0.1789923906326294, 0.9411764740943909]

#### Testing using samples

In [50]:
import numpy as np

sample=x_test[0]
sample=np.reshape(sample,(1,30))

In [52]:
model.predict(sample)

array([[1.3219788e-10]], dtype=float32)

In [61]:
model.predict(sample)[0][0]

0.7961798

In [54]:
if model.predict(sample)>0.5:
    print("Benign")
else:
    print("Melignant")

Melignant


In [66]:
for i in range(30):
    sample=x_test[i]
    sample=np.reshape(sample,(1,30))
    
    if model.predict(sample)[0][0]>0.5:
        print("-Benign")
    else:
        print("-Melignant")
    
    if y_test[i]==1:
        print("*Benign*")
    else:
        print("*Melignant*")
    print("----------")    

-Melignant
*Melignant*
----------
-Benign
*Melignant*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Benign*
----------
-Benign
*Melignant*
----------
-Melignant
*Melignant*
----------
-Melignant
*Melignant*
----------


In [6]:
print()